### ISSUE TITLE
Language editor can fail due to PHP's max_input_vars setting

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#1699]
The language editor in the admin center can fail at times due to PHP's "max_input_vars" setting. The reason for this is that for each language string in the file, SMF sends two values to the server: one containing the string's original value and one containing the value sent from the form (edited or not). Then, if the value sent from the form is the same as the original value, we don't change that string. This limits the number of calls to `cleanLangString()` and also means we don't have to save anything if nothing was actually changed.

The problem is, this causes the number of $_POST items to grow to a ridiculous number for larger language files, and, in some cases, will prevent you from being able to edit certain language files (I ran into this issue with the Admin language file, which has well over 500 language strings in it).

There are about 3 ways we can handle this:
1. Add .htaccess and .user.ini files to the directories as needed to increase input_max_vars.
2. Split up some entries in the Admin language file (and others as needed) to prevent them from having so many language strings
3. Stop the comparison and just assume that everything has changed, even if it hasn't.

I would assume things were done this way for a reason (besides "don't save changes to the file if nothing actually changed"), so I wanted further input on this situation before we decide how to fix it (or even if it should be fixed).

**Comment by Arantor** [comment]
If you're going to keep this and not split language files up, perhaps the solution is to force use of JS for it and have JS detect which strings get changed - and only submit the form with the ones that are changing.

**Comment by Oldiesmann** [comment]
I'm not entirely sure how that would be done to be honest with you, but that could be a possibility as well.

Splitting up language files is probably the best route here, at least for Admin. I'll have to look and see what other files (if any) are affected by this as well - possibly index since that's another big one.

**Comment by Arantor** [comment]
Have fun splitting up index.

**Comment by Oldiesmann** [comment]
Yeah, I know it's not going to be easy to split up all the large language files (and in the case of index may not be possible at all), but it's something I at least want to look into. The JavaScript option is a possibility as well, as much as I hate having things that may not work properly without JavaScript.

**Comment by Arantor** [comment]
On the user side, sure. On the admin side you can get away with it a bit more.

**Comment by XinYenFon** [comment]
Since you are tracking in-build language editor issues here; I take this chance to move another issue on Mantis to here :P 

0003947: Minor issues with language editor in SMF admin center
I was playing around with the language editor in the admin center in 2.0, and see a few issues I think we should address:
1. There is no way to edit the "EmailTemplates" language file from the admin center, even though this is likely to be a commonly edited file.
2. There is no way to add new language strings to an existing file. Again, this is something that many users will want and find useful, particularly those with a UTF-8 language pack installed. Most mods only support the English language, and many don't even support UTF-8 language files.
3. Random (?) ordering. The list of files you can edit seems to be in a random order - it should be in alphabetical order for best results.

I realize 2.0 is feature locked, but I think we should make these changes in order to make the editor much more useful.

Mantis: http://dev.simplemachines.org/mantis/view.php?id=3947

**Comment by Arantor** [comment]
Point 1 should not be true any more.

**Comment by Oldiesmann** [comment]
1. This is no longer true.
2. Looking at the code the other day, I discovered that this is actually possible. You just add them (each on a new line) in the textbox for one of the existing strings.
3. I believe this issue has been resolved now too.

**Comment by albertlast** [comment]
Can we close this issue?

**Comment by Sesquipedalian** [comment]
The original issue is still a problem, but I think I can fix it and improve the system overall.

**Comment by albertlast** [comment]
When i read correctly we talk here about a "tool" which exists not in smf2.1?

**Comment by frandominguezl** [comment]
I don't really understand this issue. Is it related to SMF's Language Editor?

**Comment by Arantor** [comment]
No, it's related to the ability to edit language strings inside SMF itself.

It's so obvious that almost no one knows it exists.

Go to the admin area, to Edit Languages, click a language. Notice in the corner is a drop down. Pick an item from the drop down, observe you are now presented with an editing page for that language file.

First time I tried to show this to someone, they asked me if the page was broken, because the UI is that confusing.

**Comment by Sesquipedalian** [comment]
> It's so obvious that almost no one knows it exists.
> [...]
> First time I tried to show this to someone, they asked me if the page was broken, because the UI is that confusing.

#4730 doesn't make the Edit Language Entries feature any easier to find, but it should make it a lot easier to use.
