### ISSUE TITLE
font-weight not correct in all browsers

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2155]
apparently some css calls for font-weight are asking for a weight that is not clearly classified as bold.

one for example

```
div.info .subject {
    font-weight: 600;
    font-size: 1.1em;
    color: #A85400;
}
```

if the font weight is 700 it will show as bold in firefox otherwise it is not bold.

for more info i found http://stackoverflow.com/questions/17414815/firefox-ignoring-css-font-weight-property

@Antes

**Comment by illori** [comment]
seems different browsers show more or less bold. in chrome it shows almost no bold, where ff shows more and opera even more.

**Comment by XinYenFon** [comment]
https://code.google.com/p/chromium/issues/detail?id=335050

This is a Chrome issue.

**Comment by XinYenFon** [comment]
My vote goes to keep things as is, because there is a visible difference between Font-weight: 100/600/normal/bold but I'm not against changing 100 to normal, 600 to bold.

**Comment by Oldiesmann** [comment]
How much of a notable difference is there between 600 and 700? If it's not much we could just bump it to 700 maybe.

**Comment by XinYenFon** [comment]
![screenshot-localhost 2014-08-03 22-28-20](https://cloud.githubusercontent.com/assets/1669995/3791563/6a08bc40-1b44-11e4-8e9b-eb296c2a3240.png)

**Comment by illori** [comment]
if you were to check how 600 looks in different browsers, it is a good bit different, try opera and firefox.

if you change it to 700 it is the same in opera and firefox.

![](https://imagizer.imageshack.us/v2/426x124q90/905/RQVAab.png)

at 600 opera 12 on the left ff on the right

**Comment by XinYenFon** [comment]
This problem seems fixed in Chrome 39 according to their developers https://code.google.com/p/chromium/issues/detail?id=335050#c35

**Comment by illori** [comment]
that does not fix the issue that the font weight does not look the same across different browsers.

**Comment by XinYenFon** [comment]
I don't see difference in ie11 & ff32 after chrome 39 we'll look again

-----Original Message-----

**Comment by illori** [comment]
compare opera 12.17 and ff32 as seen in the screenshot i posted above.

**Comment by XinYenFon** [comment]
Opera 12 is not the latest version, try with 2x series, we can't support old browsers.

-----Original Message-----

**Comment by illori** [comment]
many people still use opera 12, it does not hurt to support it. i am not upgrading just for a minor css issue.

**Comment by XinYenFon** [comment]
In China dozens of people using ie6-7, since the visual change is visible clearly, this is not SMF bug. Opera 12 users best learn to live with it.

-----Original Message-----

**Comment by Oldiesmann** [comment]
In my opinion there's nothing wrong with changing the font weight to 700, since even recent versions of Chrome have that issue.

**Comment by Xarcell** [comment]
Font-weight consistency has been an issue for may years; as far back as I can remember. There is no fixing it. You just have to go with the lesser of the evils.

**Comment by live627** [comment]
Hello there, Xarcell.

What do you recommend we use? A name or a number?

**Comment by Xarcell** [comment]
It doesn't really matter, it will be inconsistent across all browsers regardless. That being said,  would just leave it as is. In webkit browsers, sometimes it helps to add -webkit-font-smoothing: antialiased; for blurry or thin on dark backgrounds.

For small text with font-weighting, I use letter-spacing: 1px; just to make it more legible.

Neither methods "fix" anything though.

**Comment by live627** [comment]
So I guess it's like houses - different in their own way, but serve the
same purpose at the end of the day.

I guess this can be closed now.
