### ISSUE TITLE
Editor problem ??

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#458]
If you have enabled "show WYSIWYG" as default in you profile and start a new topic or edit a existing, the background of the editor is black .. Uhm ?
One toggle BBC - WYSIWYG brings back the white background .. Ahhh :-)

I don't have a fix for that, because I have not enough time to show on the editor.

**Comment by Oldiesmann** [comment]
What browser are you using? I'm unable to reproduce it (Chrome, Firefox and IE10 on Windows 7).

**Comment by PortaMx** [comment]
Firefox 21.0 on a Windows XP System.
Same effect on our Life Site http://feline-networks.com
With Chrome (28.0.1500.52 beta-m) it works correct...

**Comment by illori** [comment]
checked and saved "Show WYSIWYG editor on post page by default." in look and layout tested in ff21 no issues with win 7.

**Comment by PortaMx** [comment]
Please .. test on our Life Site htp://feline-networks.com with ff21

**Comment by illori** [comment]
why would your install be any different then any other? i have never seen the issue with ff.

**Comment by PortaMx** [comment]
fixed the issue .. see #472

**Comment by Oldiesmann** [comment]
I'm glad that fixes it for you, but I still don't understand why that fixes it or what the problem is here.

The jquery.sceditor.css file specifies a white background for the editor. Unless jquery.sceditor.default.css specifies a background color for the editor (which, as far as I can tell, it doesn't), the one from jquery.sceditor.css should apply.

Does it still occur on other SMF 2.1 installs? (see http://smfgit.oldiesmann.us if you need another one to test it on)?

Illori and I have both tested it with Firefox and can't reproduce it. I don't mind merging in the changes, but there's no point in doing so if nobody else can reproduce this.

**Comment by PortaMx** [comment]
Just tested on your site .. same problem .. I have add a screen shot to the post ...

By the way .. the fix what I send is not 100% .. it's need a little bit more fiddeling on the CSS .. so I will make more test. The pullrequest for this you can canceled. I will test for a better solution. 
Thanks, Fel

**Comment by illori** [comment]
![Alt Text](http://imageshack.us/a/img28/5273/76d4.png)

using ff 22 with windows xp VM with no addons in ff

**Comment by Oldiesmann** [comment]
Not an actual bug per the latest comments on #472.
