### ISSUE TITLE
This ban is not set to expire

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4601]
seems this message shows up in a ban even if the ban is set to expire in a set amount of time. i set a ban to expire after 1 day, the user is shown the standard ban message and at the end of the message it says the This ban is not set to expire, which is not correct. it even shows this on the who's online page.

**Comment by MissAllSunday** [comment]
Seems this issue has been resolved, cannot replicate it

**Comment by illori** [comment]
this is still happening. i banned my test user, got the message it was banned, then i refreshed the page and the message says 

> Sorry Guest, you are banned from using this forum!
test
This ban is not set to expire.

the ban is set to expire in 2 days.

the message is also showing up in the who's online page as well.

**Comment by MissAllSunday** [comment]
Ah yes, it happens when the page is refreshed, will take a look at it.
