### ISSUE TITLE
Guests can still see hidden boards

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5265]
I set up a category for admin use only, and in that category set up a board. Board has all user groups unchecked, but guest can still see that board, and see the latest post subject in that board.  If they click to view the post they have to log in.  Being able to see the subject in the admin board isn't great.  I can't hide the board completely, like I can in 2.0.15

Nightly build version https://github.com/SimpleMachines/SMF2.1/compare/450da88...release-2.1

**Comment by albertlast** [comment]
How do you define that guest had no access?

**Comment by frandominguezl** [comment]
### Steps to reproduce
1. Create a new category
2. Inside that category, create a new board and uncheck all "Allowed Groups" fields
3. Logout and you'll be able (as guest) to see that the board exists

Actually, it seems that everyone is able to see every board even if they don't have access to it. As "Allowed Groups" says, that setting is just to access the board, not to view it.

**Comment by albertlast** [comment]
In my test the bug get fixed by the pr #5153 
maybe @Sesquipedalian you should add the pr now and not later.

**Comment by frandominguezl** [comment]
That PR doesn't solve this issue. Once applied, guests can still see boards that they don't have access to.

**Comment by albertlast** [comment]
The problem is "save" function,
so you need switch once the right of the board and then the rules get cleaned.

**Comment by lurkalot** [comment]
>           The problem is "save" function,
> so you need switch once the right of the board and then the rules get cleaned.

Do You mean check all the boxes and save, then uncheck them and save?  That doesn't work for me, unless I'm not understanding you correctly.

**Comment by albertlast** [comment]
yes but first you need to apply the pr(or the changes of the pr).

**Comment by frandominguezl** [comment]
Alright, it works after checking and then unchecking the boxes.

**Comment by lurkalot** [comment]
>           yes but first you need to apply the pr(or the changes of the pr).

OK, thanks.  Then I'll wait until those fixes are added and test again then.
