### ISSUE TITLE
Upgrader does not migrate 'warning_show' setting to 'view_warning_*' permissions

### ISSUE THREAD

**Issue by leashadav** [SimpleMachines/SMF#6974]
after smf site was updated from 2.0.18 to 2.1 rc4
members who have been warned, the warning no longer shows up under their usernames in posts
(muted/watched/etc)

**Comment by BrickOzp** [comment]
Must be a smf.org issue. I can see it on my test forum

**Comment by leashadav** [comment]
yes it is, I was asked to open a ticket here about it for the devs to look at

**Comment by jdarwood007** [comment]
Are they showing up now?

After the upgrade no custom profile fields where showing.  I saved a single custom profile field and they all started to show up.
I'm thinking a bug in the upgrader exists that is being resolved by just saving the custom profile fields page and making things show up.

**Comment by leashadav** [comment]
unfortunately no it's still not showing up
![Untitled](https://user-images.githubusercontent.com/55554713/130086009-f8da1a8b-5dc7-4f26-9366-d59c455a1e4d.png)

**Comment by BrickOzp** [comment]
Can you double check that Warning status is active under Profile fields

**Comment by jdarwood007** [comment]
It is

**Comment by Sesquipedalian** [comment]
Can you double check whether the affected membergroups have the `view_warning_any` permission?

**Comment by jdarwood007** [comment]
The user only has issue_warning.  I can't find any other related warning permissions.

Did this change from 2.0 or was lost somehow?

**Comment by Sesquipedalian** [comment]
<img width="1179" alt="Screen Shot 2021-08-20 at 2 16 19 PM" src="https://user-images.githubusercontent.com/191731/130289165-e6913d91-bcd6-4c5c-83d2-d251a08379f8.png">

The `view_warning_any` and `view_warning_own` permissions are new in SMF 2.1, distinct from the `issue_warning` permission. They were added in #1465 as a permissions-based replacement for the `$modSettings['warning_show']` setting. However, it looks like nothing was done at the time to migrate `$modSettings['warning_show']` to the new permissions in the upgrader. We should probably fix that.

**Comment by jdarwood007** [comment]
I agree.  The end result is we will fix permissions on this manually, but it introduced a disconnect for admins/moderators after the upgrade removed something they didn't expect.

**Comment by leashadav** [comment]
thank you, seems to be working on smf now
